version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-${APP_ENV}
    volumes:
      - ./:/usr/src/app/
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db
  db:
    image: postgres:9.4
    env_file:
      - .env
    volumes:
      - logdme_data:/var/lib/postgresql/data

volumes:
  logdme_data:
    external: true
